CREATE TABLE BRANCH(
     BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
     BR_NAME VARCHAR(30)
);
INSERT INTO BRANCH(BR_NAME) VALUES('CHENNAI');  -- 1
INSERT INTO BRANCH(BR_NAME) VALUES('KANNIYAKUMARI');  -- 2
INSERT INTO BRANCH(BR_NAME) VALUES('THENI');   -- 3 
INSERT INTO BRANCH(BR_NAME) VALUES('MADURAI');   -- 4
INSERT INTO BRANCH(BR_NAME) VALUES('CHENNAI'); 
INSERT INTO BRANCH(BR_NAME) VALUES('VILUPURAM'); -- 5
SELECT * FROM BRANCH;
CREATE TABLE EMPLOYEE(
     EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
	 ENAME VARCHAR(30) NOT NULL,
     JOB_DESC VARCHAR(20),
     SALARY INT ,
     BRANCH_ID INT , 
     CONSTRAINT FOREIGN_KEY_CONSTRAINT FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);
ALTER TABLE EMPLOYEE DROP CONSTRAINT FOREIGN_KEY_CONSTRAINT ;
SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;
DROP TABLE EMPLOYEE;
INSERT INTO EMPLOYEE VALUES (1,'ABIINANTH','SDE',10000,1);
INSERT INTO EMPLOYEE VALUES (2,'JAISURYA','SDE',20000,4);
INSERT INTO EMPLOYEE VALUES (3,'RUBHA','SDE',10000,3);
INSERT INTO EMPLOYEE VALUES (4,'JAYASURYA','SDE',30000,1);
INSERT INTO EMPLOYEE VALUES (5,'SIBIRAJ','UIUX',30000,3);
INSERT INTO EMPLOYEE VALUES (6,'NAVEEN','TRAVELLER',20000,3);
INSERT INTO EMPLOYEE VALUES (7,'KARTHI','SDE',10000,5);
INSERT INTO EMPLOYEE VALUES (8,'DIJESH','NURSING',70000,2);
INSERT INTO EMPLOYEE VALUES (9,'JERNISH','ANESTHESHIA',30000,1);
INSERT INTO EMPLOYEE VALUES (10,'ABIRAM','ARMY',90000,2);
INSERT INTO EMPLOYEE VALUES (11,'ABIRAM1','ARMY',90000,null);
INSERT INTO EMPLOYEE VALUES (12,'ABIRAM2','ARMY',90000,null);


-- INNER JOIN 
CREATE VIEW INNERJOINTVIEW AS 
SELECT EMPLOYEE.EMP_ID,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,EMPLOYEE.SALARY,BRANCH.BR_NAME 
FROM EMPLOYEE 
INNER JOIN BRANCH ON EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID;


SELECT EMPLOYEE.EMP_ID,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,EMPLOYEE.SALARY,BRANCH.BR_NAME 
FROM EMPLOYEE 
INNER JOIN BRANCH ON EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID AND EMPLOYEE.BRANCH_ID!=1 AND EMPLOYEE.BRANCH_ID!=5;
-- LEFT JOIN 

SELECT EMPLOYEE.EMP_ID,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,EMPLOYEE.SALARY,BRANCH.BR_NAME 
FROM EMPLOYEE 
LEFT JOIN BRANCH ON EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID;


-- RIGHT JOIN 
SELECT EMPLOYEE.EMP_ID,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,EMPLOYEE.SALARY,BRANCH.BR_NAME 
FROM EMPLOYEE 
RIGHT JOIN BRANCH ON EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID; -- IT WILL ALSO SHOW VILUPURAM AND IT IS BECAUSE IT IS THE RIGHT JOIN 



-- QUESTION BR_NAME , EMP_COUNT 
SELECT 
    B.BR_NAME,  -- use the real column name here
    COUNT(E.EMP_ID) AS EMP_COUNT
FROM BRANCH AS B
JOIN EMPLOYEE AS E 
    ON B.BRANCH_ID = E.BRANCH_ID
GROUP BY E.BRANCH_ID;


SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;

SELECT b.br_name,COUNT(e.emp_id)
FROM branch as b
JOIN employee as e
ON b.branch_id = e.branch_id
GROUP BY e.branch_id;

SELECT COUNT(E.EMP_ID) FROM EMPLOYEE AS E GROUP BY SALARY;

-- UNION TABLE 


CREATE TABLE clients (
client_id INT PRIMARY KEY AUTO_INCREMENT,
location VARCHAR(30) NOT NULL,
addr VARCHAR(200) );


INSERT INTO clients VALUES(1,"NewYork","25 10th Block");
INSERT INTO clients VALUES(2,"Coimbatore","120 15th Block");
INSERT INTO clients VALUES(3,"London","21 ABC Road");

SELECT * FROM CLIENTS;
SELECT * FROM BRANCH;

SELECT * FROM branch
UNION 
SELECT * FROM clients;

ALTER TABLE CLIENTS DROP COLUMN ADDR ;
DELETE FROM  BRANCH   WHERE BRANCH_ID > 3; 
	
-- subqueries 

SELECT * FROM EMPLOYEE
WHERE BRANCH_ID=(
SELECT BRANCH_ID FROM BRANCH 
WHERE BR_NAME="CHENNAI");  -- THIS IS AWESOME MAN --- JUST WOW
                  
SELECT ENAME , SALARY FROM EMPLOYEE WHERE SALARY=(
SELECT MIN(SALARY) FROM EMPLOYEE);   




-- EXCERCISE 


SELECT  * FROM EMPLOYEE 
WHERE BRANCH_ID <> ALL(
SELECT BRANCH_ID FROM BRANCH 
WHERE BR_NAME IN ("CHENNAI","THENI"));


SELECT * FROM INNERJOINTVIEW;